"""add starter pool flag

Revision ID: cfc22b084688
Revises: 6213b92ca4a6
Create Date: 2026-08-19 17:41:10.878691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc22b084688'
down_revision: Union[str, Sequence[str], None] = '6213b92ca4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'players',
    sa.Column(
        'starter_pool',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('true')
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'starter_pool')
    # ### end Alembic commands ###
